//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNghi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKITHAMGIA
    {
        public int IDHN { get; set; }
        public int IDUSER { get; set; }
        public int TRANGTHAI { get; set; }
        public System.DateTime THOIGIANDK { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual HOINGHI HOINGHI { get; set; }
    }
}
