//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNghi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOINGHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOINGHI()
        {
            this.CHITIETADMINs = new HashSet<CHITIETADMIN>();
            this.DANGKITHAMGIAs = new HashSet<DANGKITHAMGIA>();
        }
    
        public int IDHN { get; set; }
        public int IDDD { get; set; }
        public string TENHN { get; set; }
        public string MOTANGANHN { get; set; }
        public string MOTACHITIETHN { get; set; }
        public string HINHANH { get; set; }
        public System.DateTime THOIGIANBATDAU { get; set; }
        public System.DateTime THOIGIANKETTHUC { get; set; }
        public int SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETADMIN> CHITIETADMINs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKITHAMGIA> DANGKITHAMGIAs { get; set; }
        public virtual DIADIEMTOCHUC DIADIEMTOCHUC { get; set; }
    }
}
