//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNghi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQuanLiHoiNghiEntities : DbContext
    {
        public DBQuanLiHoiNghiEntities()
            : base("name=DBQuanLiHoiNghiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETADMIN> CHITIETADMINs { get; set; }
        public virtual DbSet<DANGKITHAMGIA> DANGKITHAMGIAs { get; set; }
        public virtual DbSet<DIADIEMTOCHUC> DIADIEMTOCHUCs { get; set; }
        public virtual DbSet<HOINGHI> HOINGHIs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
