//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNghi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CHITIETADMINs = new HashSet<CHITIETADMIN>();
            this.DANGKITHAMGIAs = new HashSet<DANGKITHAMGIA>();
        }
    
        public int IDUSER { get; set; }
        public string TENUSER { get; set; }
        public string PASSWORD { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string HINHANH { get; set; }
        public string LOAIUSER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETADMIN> CHITIETADMINs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKITHAMGIA> DANGKITHAMGIAs { get; set; }
    }
}
